version: '3'
services:
  ecommerce-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    networks:
      - siteware_ecommerce-network

networks:
  siteware_ecommerce-network:
    external:
      name: siteware_ecommerce-network
